### DISCUSSION TITLE
Unable to get Apollo3 up and running

### DISCUSSION THREAD

**Discussion by Bjoernsen** [GMOD/Apollo3#431] [Q&A]
Hi,
Currently, I am trying to start apollo with docker compose. Unfortunately, I get the error message `DNS lookup failure for: apollo-collaboration-server` during the "login". What did I wrong?

Best,
Bjoern

![image](https://github.com/user-attachments/assets/62a7dc15-fd9e-4c45-adab-aad0306bdf8d)

Here are the Dockerfile, compose.yml, .env, and some logs. Unfortunately, I am befind a firewall/proxy and I had do modify the Dockerfile a bit. Changes are commented with `#CHANGED`.

# Dockerfile
```Dockerfile
# CHANGED: Your image is not able to access the internet to download some files
FROM SOME-INTERNAL-IMAGE-WITH-INTERNET-ACCESS AS downloader
ARG JBROWSE_VERSION
ARG APOLLO_VERSION
ARG FORWARD_HOSTNAME
ARG FORWARD_PORT
ARG URL

RUN apt-get update && apt-get install -y wget

RUN mkdir /download
WORKDIR /download
RUN wget https://github.com/GMOD/jbrowse-components/releases/download/v$JBROWSE_VERSION/jbrowse-web-v$JBROWSE_VERSION.zip
RUN wget --output-document=- --quiet https://registry.npmjs.org/@apollo-annotation/jbrowse-plugin-apollo/-/jbrowse-plugin-apollo-$APOLLO_VERSION.tgz | \
  tar --extract --gzip --file=- --strip=2 package/dist/jbrowse-plugin-apollo.umd.production.min.js

FROM httpd:alpine
ARG JBROWSE_VERSION
ARG APOLLO_VERSION
ARG FORWARD_HOSTNAME
ARG FORWARD_PORT
ARG URL

COPY <<EOF /usr/local/apache2/conf/httpd.conf.append
LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_http_module modules/mod_proxy_http.so
LoadModule proxy_wstunnel_module modules/mod_proxy_wstunnel.so
# CHANGED:  I got some CORS issues, but they should not be related to the issue
LoadModule headers_module modules/mod_headers.so
ServerName localhost

# CHANGED:  I got some CORS issues, but they should not be related to the issue
Header set Access-Control-Allow-Origin "*"

ProxyPassMatch "^/apollo/(.*)$" "http://${FORWARD_HOSTNAME}:${FORWARD_PORT}/\$1" upgrade=websocket connectiontimeout=3600 timeout=3600
ProxyPassReverse "/apollo/" "http://${FORWARD_HOSTNAME}:${FORWARD_PORT}/"
EOF
COPY <<EOF /usr/local/apache2/htdocs/config.json
{
  "configuration": {
    "theme": {
      "palette": {
        "primary": {
          "main": "#24264a"
        },
        "secondary": {
          "main": "#6f8fa2"
        },
        "tertiary": {
          "main": "#1e4b34"
        },
        "quaternary": {
          "main": "#6b4e2b"
        }
      }
    }
  },
  "plugins": [
    {
      "name": "Apollo",
      "url": "/jbrowse-plugin-apollo.umd.production.min.js"
    }
  ],
  "internetAccounts": [
    {
      "type": "ApolloInternetAccount",
      "internetAccountId": "apolloInternetAccount",
      "name": "My Apollo Server",
      "description": "A server for my annotations",
      "domains": [
        "${URL}:9980" # CHANGED: added the port 9980, because I cannot use 80. Already in use
      ],
      "baseURL": "${URL}:9980/apollo/"  # CHANGED: added the port 9980, because I cannot use 80. Already in use
    }
  ],
  "defaultSession": {
    "name": "Apollo Demo",
    "views": [
      {
        "type": "LinearGenomeView"
      }
    ]
  }
}
EOF
WORKDIR /usr/local/apache2/htdocs/

# CHANGED: here I copy the already downloaded files
COPY --from=downloader /download/* .

RUN <<EOF
set -o errexit
set -o nounset
set -o pipefail
cat /usr/local/apache2/conf/httpd.conf.append >> /usr/local/apache2/conf/httpd.conf
# CHANGED
unzip -o jbrowse-web-*.zip
rm jbrowse-web-*.zip
EOF
```

# compose.yml
```
# https://github.com/GMOD/Apollo3/blob/main/docs/deployment.md
name: apollo-demo-site

services:
  apollo-collaboration-server:
    image: ghcr.io/gmod/apollo-collaboration-server
    depends_on:
      mongo-node-1:
        condition: service_healthy
    env_file: .env
    environment:
      MONGODB_URI: mongodb://mongo-node-1:27017,mongo-node-2:27018/apolloDb?replicaSet=rs0
      FILE_UPLOAD_FOLDER: /data/uploads
      ALLOW_GUEST_USER: true
      GUEST_USER_ROLE: admin
      URL: http://localhost
      JWT_SECRET: change_this_value
      SESSION_SECRET: change_this_value
    ports:
      - 3999:3999
    volumes:
      - uploaded-files-volume:/data/uploads

  client:
    build:
      args:
        APOLLO_VERSION: 0.1.19 # CHANGED: latest version
        JBROWSE_VERSION: 2.14.0 # CHANGED: latest version
        FORWARD_HOSTNAME: apollo-collaboration-server
        FORWARD_PORT: 3999
        URL: http://localhost
      context: .
    depends_on:
      - apollo-collaboration-server
    ports:
      - '9980:80' # CHANGED: port 80 to 9980

  mongo-node-1:
    image: mongo:7
    command:
      - '--replSet'
      - rs0
      - '--bind_ip_all'
      - '--port'
      - '27017'
    healthcheck:
      interval: 30s
      retries: 3
      start_interval: 5s
      start_period: 2m
      test: |
        mongosh --port 27017 --quiet --eval "
        try {
          rs.status()
          console.log('replica set ok')
        } catch {
          rs.initiate({
            _id: 'rs0',
            members: [
              { _id: 0, host: 'mongo-node-1:27017', priority: 1 },
              { _id: 1, host: 'mongo-node-2:27018', priority: 0.5 },
            ],
          })
          console.log('replica set initiated')
        }
        "
      timeout: 10s
    ports:
      - '27017:27017'
    volumes:
      - mongo-node-1_data:/data/db
      - mongo-node-1_config:/data/configdb

  mongo-node-2:
    image: mongo:7
    command:
      - '--replSet'
      - rs0
      - '--bind_ip_all'
      - '--port'
      - '27018'
    ports:
      - '27018:27018'
    volumes:
      - mongo-node-2_data:/data/db
      - mongo-node-2_config:/data/configdb

volumes:
  mongo-node-1_config: null
  mongo-node-1_data: null
  mongo-node-2_config: null
  mongo-node-2_data: null
  uploaded-files-volume: null
```

# .env
```
  ##############
  ## REQUIRED ##
  ##############

  # URL
  URL=http://localhost:9980

  # MongoDB connection
  MONGODB_URI=mongodb://127.0.0.1:27017/apolloDb
  # Alternatively, can be a path to a file with the URI
  # MONGODB_URI_FILE=/run/secrets/mongodb-uri

  # Output folder for uploaded files
  FILE_UPLOAD_FOLDER=./data/uploads

  # Secret used to encode JWT tokens
  JWT_SECRET=some-secret
  # Alternatively, can be a path to a file with the client secret
  # JWT_SECRET_FILE=/run/secrets/jwt-secret

  # Secret used to encode express sessions
  SESSION_SECRET=some-other-secret
  # Alternatively, can be a path to a file with the session secret
  # SESSION_SECRET_FILE=/run/secrets/session-secret

  ##############################################################################
  ## To enable users to log in, you need either (or both) Google or Microsoft ##
  ## OAuth configured. Without them, only userless guest access is possible.  ##
  ##############################################################################

  # Google client id and secret.
  # GOOGLE_CLIENT_ID=
  # Alternatively, can be a path to a file with the client ID
  # GOOGLE_CLIENT_ID_FILE=/run/secrets/google-client-id
  # GOOGLE_CLIENT_SECRET=
  # Alternatively, can be a path to a file with the client secret
  # GOOGLE_CLIENT_SECRET_FILE=/run/secrets/google-client-secret

  # Microsoft client id and secret.
  # MICROSOFT_CLIENT_ID=
  # Alternatively, can be a path to a file with the client ID
  # MICROSOFT_CLIENT_ID_FILE=/run/secrets/microsoft-client-id
  # MICROSOFT_CLIENT_SECRET=
  # Alternatively, can be a path to a file with the client secret
  # MICROSOFT_CLIENT_SECRET_FILE=/run/secrets/microsoft-client-secret

  ##############
  ## OPTIONAL ##
  ##############

  # Application port, defaults to 3999
  # PORT=3999

  # Enable all CORS requests, defaults to false
  CORS=true

  # Comma-separated list of log levels to output
  # Possible values are: error, warn, log, debug, verbose.
  # Defaults to error,warn,log
  # LOG_LEVELS=error,warn,log

  # Reference sequence chunk size, defaults to 262144 (256 KiB)
  # CHUNK_SIZE=262144

  # Default new user role, possible values are admin, user, readOnly, and none
  # Defaults to none
  # DEFAULT_NEW_USER_ROLE=none

  # Whether to broadcast users locations, defaults to true
  BROADCAST_USER_LOCATION=false

  # Whether to allow guest users who do not have to log in, defaults to false
  ALLOW_GUEST_USER=true
  # If guest users are allowed, what role will they have
  # Possible values are admin, readOnly and user; defaults to readonly
  # CHANGED: I would like to play around and currently, I cannot use Google, or Microsoft for log in
  GUEST_USER_ROLE=admin

  # Whether to allow a root user. Root users cannot log in to the user interface,
  # but can be used in the Apollo CLI as an account that can log in without
  # needing an identity provider (such as Google). Defaults to false.
  # ALLOW_ROOT_USER=false
  # The username for the root user, if allowed
  # ROOT_USER_NAME=root
  # The password for the root user, if allowed
  # ROOT_USER_PASSWORD=
  # Alternatively, can be a path to a file with the root password
  # ROOT_USER_PASSWORD_FILE=/run/secrets/root-user-password

  # Apollo by default uses The Sequence Ontology. You can override this by
  # providing a path to an ontology file in the OBO Graphs JSON format. You can
  # use `robot` to convert an OBO or OWL to OBO Graphs JSON.
  # http://robot.obolibrary.org/convert
  # ONTOLOGY_FILE = '/data/ontology.json'

  # Comma-separated list of Apollo plugins to use
  # PLUGIN_URLS=https://example.com/apollo-plugin-example.umd.production.min.js
  # Alternatively, can be a path to a file with a list of plugin URLs, one URL per
  # line
  # PLUGIN_URLS_FILE=/data/plugin-urls
```

# some logs
```
client-1                       | [Fri Aug 30 05:53:45.554136 2024] [proxy:error] [pid 92:tid 97] (EAI 3)Try again: [client 172.27.1.1:56780] AH00898: DNS lookup failure for: apollo-collaboration-server returned by /apollo/socket.io/, referer: http://localhost:9980/?session=local-PMjTvYYxvjPCeYN5qxUD
```
