### ISSUE TITLE
Google OAuth not working

### ISSUE THREAD

**Issue by johannesnicolaus** [GMOD/Apollo3#378]
Hi all, I tried to run Apollo3 on AWS and it worked fine, but I just somehow could not make the google login to work. 

I modified `apollo.env` to include the client ID and secret. However when I ran `docker compose restart` and `docker compose cp ./config.json jbrowse-web:/usr/local/apache2/htdocs/` and reloaded on the browser (after removing cache) the google login is still greyed out.

I'm not really sure if I have done something wrong, I followed all the steps in the `/docs/deployment.md`

**Comment by jlqfab** [comment]
Hi @garrettjstevens, I would like to follow up on this issue as I have been having the same problem that the Google (and Microsoft) OAuth login is grayed out, allowing only the guest login.

I followed the same instructions at `/docs/deployment.md`, but had to make a few minor changes to get Apollo3 up and running, primarily requiring `hostname` to be configured for the `mongodb` container (otherwise Docker uses an auto generated hostname which caused a hostname mismatch in the mongodb replica set).

My `docker-compose.yml` contains the following:
```
services:
  apollo-collaboration-server:
    image: public.ecr.aws/p1r0y7k4/apollo-collaboration-server-alpha:latest
    container_name: apollo-collaboration-server-1
    hostname: apollo-collaboration-server-1
    volumes:
      - uploaded-files-volume:/data/uploads
    ports:
      - 3999:3999
    env_file: /home/ubuntu/apollo/apollo.env
    depends_on:
      mongodb-init:
        condition: service_completed_successfully

  jbrowse-plugin-apollo:
    image: public.ecr.aws/p1r0y7k4/jbrowse-plugin-apollo-alpha:latest
    container_name: jbrowse-plugin-apollo-1
    ports:
      - 9000:80

  jbrowse-web:
    image: public.ecr.aws/p1r0y7k4/jbrowse-web-apollo-alpha:latest
    container_name: jbrowse-web-apollo-1
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/config:/usr/local/apache2/htdocs/data

  mongodb:
    image: mongo
    container_name: apollo-mongodb-1
    hostname: apollo-mongodb-1
    volumes:
      - mongodb-volume:/data/db
    command: --replSet rs0

  # this container will exit after initializing the replica set
  mongodb-init:
    image: mongo
    container_name: apollo-mongodb-init-1
    depends_on:
      - mongodb
    command:
      mongosh mongodb://apollo-mongodb-1:27017 --eval 'try {rs.initiate();} catch {}'

volumes:
  mongodb-volume: null
  uploaded-files-volume: null
```

My `config.json` was configured with the following changes:
```
  "plugins": [
    {
      "name": "Apollo",
      "url": "http://ubuntu22-test.genome.edu.au:9000/jbrowse-plugin-apollo.umd.production.min.js"
    }
  ],
  "internetAccounts": [
    {
      "type": "ApolloInternetAccount",
      "internetAccountId": "apolloInternetAccount",
      "name": "Apollo Server",
      "description": "Apollo server for my organization",
      "baseURL": "http://ubuntu22-test.genome.edu.au:3999"
    }
  ],
```

The `apollo.env` was configured with (unused settings omitted):
```
# URL
URL=http://ubuntu22-test.genome.edu.au

# MongoDB connection
MONGODB_URI=mongodb://apollo-mongodb-1:27017/apolloDb

# Output folder for uploaded files
FILE_UPLOAD_FOLDER=/data/uploads

# Secret used to encode JWT tokens
JWT_SECRET=<SECRET>

# Secret used to encode express sessions
SESSION_SECRET=<SECRET>

# Google client id and secret.
GOOGLE_CLIENT_ID=<NUMERIC>-<ALPHANUM>.apps.googleusercontent.com
GOOGLE_CLIENT_SECRET=GOCSPX-<SECRET>-

# Comma-separated list of log levels to output
# Possible values are: error, warn, log, debug, verbose.
# Defaults to error,warn,log
LOG_LEVELS=error,warn,log,debug

# Whether to allow guest users who do not have to log in, defaults to false
ALLOW_GUEST_USER=true
# If guest users are allowed, what role will they have
# Possible values are admin, readOnly and user; defaults to readonly
GUEST_USER_ROLE=readOnly
```

I have checked that `GOOGLE_CLIENT_ID` and `GOOGLE_CLIENT_SECRET` have been set properly by examining the environment variables within the `apollo-collaboration-server` container. These were correct, but I can see no connections to Google OAuth from my Google account.

Additionally, I've examined the logs, and can see no relevant errors. The `apollo-collaboration-server` container is running properly, with logs ending at `Application is running on: http://[::1]:3999, CORS = true`. The `jbrowse-web-apollo` and `jbrowse-plugin-apollo` logs both show my connection to the web page. The `apollo-mongodb` log shows that the database is working.

Note that I also have to run `docker compose up -d` twice as per [Issues with docker compose #416 ](https://github.com/GMOD/Apollo3/issues/416).

Is there any chance someone can provide some guidance as to how to get this working? I'm happy to provide any additional information or run additional tests as required.

Thanks.
